---
- name: Start-nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
  tags:
    -lighthouse
- name: Restart Nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
  tags:
    -lighthouse